resource_types:
  - name: sonar-runner
    type: docker-image
    source:
      repository: cathive/concourse-sonarqube-resource
      tag: latest
resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/sharadg/blue-green-demo.git
      branch: master
  - name: code-analysis
    type: sonar-runner
    source:
      host_url: {{SC_HOST_URL}}
      login: {{SC_LOGIN_KEY}}
      organization: {{SC_ORGANIZATION}}

jobs:
  - name: build-and-analyze
    plan:
      - get: git-repo
        trigger: true
      - task: build
        file: git-repo/ci/build-artifact.yml
        params:
          base_name: blue-green-demo
      - put: code-analysis
        params:
          project_key: {{SC_PROJECT_KEY}}
          project_path: sonarqube-analysis-input
          scanner_type: maven

  - name: qualitygate
    plan:
      - get: git-repo
        passed:
          - build-and-analyze
      - get: code-analysis
        passed:
          - build-and-analyze
        trigger: true
      - task: check-sonarqube-quality-gate
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cathive/concourse-sonarqube-qualitygate-task
              tag: latest
          inputs:
            - name: code-analysis
          run:
            path: /sonarqube-qualitygate-check
            dir: code-analysis
